---
- name: Install Prometheus
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Install Loki (Log Aggregation)
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.6.1/loki-linux-amd64.zip
    dest: /usr/local/bin/loki.zip
